### ISSUE TITLE
【Question】Does piXedfit_bin average or sum the flux inside a bin?

### ISSUE THREAD

**Issue by bszzhzxyf** [aabdurrouf/piXedfit#14]
I think pixel binning should be "average of the flux". Because if we sum the flux in several pixels ,  then a bin will correspond to a larger solid angle(arcsec^2) ,or physical scale.（e.g. several kpc in a galaxy） Meanwhile, in different bins there are different pixel numbers,  so they will  represent different physical scales of a galaxy. I'm confused about whether piXedfit_bin uses average or sum.

**Comment by markliuchina** [comment]
Hi, glad to see a user in China! So far, we have already explored the code and find piXedfit satisfying for spatially-resolved analysis in CEERS imaging data. 
Anyway, I think the pixel-binning techique is one thing (see the paper from Abdurro'uf in 2017), and the photometry of each bin is another thing and that is implemented by the SED (Python version of SE). 
That is, the piXedfit may indeed sum the flux and flux_err following the SEP's methods.
You make very valid point! Actually the physical information of individual pixel will suffer the influence from the neighboring pixels due to the PSF effects. 
So far, we think the pixel-binning from piXedfit can take into consideration the PSF effects. That is, the binning maps can tell you which pixels can be brought together to form a bin and all the pixels of a certain bin should share similar physical properties (taking into account the chi-sq of the pixel SED and the S/N).
For details,  you can refer to Abdurro'uf's poster introducing piXedfit in SINICA.
I think averaging itself will break the physical information of both the bins and pixels (the distribution of pixel flux on each band may be wholly different, which may cause bias). As a result, taking the bin as a whole will be more reasonable! (think about the integrated way of photometry and SED fitting). 
If you cannot just figure out whether it is "summing" or "averaging", you can see from the plot below, the magnitude the SED become greated after binning.
![image](https://github.com/aabdurrouf/piXedfit/assets/99796331/5e33f496-0f7f-42de-bd6d-af88ebb5556e)
Hope it helps.

Best.

**Comment by aabdurrouf** [comment]
Thanks @bszzhzxyf for your question, thanks @markliuchina for helping me to answer (and nicely showing some of your results!), and sorry for my very late response. Indeed, the binning process sums up pixel fluxes (and also their uncertainties in quadrature) to increase the signal-to-noise ratios, which is the main purpose of pixel binning.
